apiVersion: v1
kind: Pod
metadata:
  name: aws-cli-checker
  namespace: <your-name> # 適宜namespaceを変更
spec:
  serviceAccountName: pod-identity-sa # Pod Identityに対応したServiceAccount名に変更
  containers:
    - name: aws-cli
      image: amazonlinux:2
      command: ["/bin/sh"]
      args:
        - -c
        - |
          yum install -y aws-cli && \
          echo "AWS CLI installed successfully!" && \
          echo "You can now run AWS CLI commands interactively." && \
          echo "Example: aws s3 ls" && \
          /bin/bash
      env:
        - name: AWS_REGION
          value: ap-northeast-1
      stdin: true
      tty: true
  restartPolicy: Never
