# rbac-owner.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-owner
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: bind-owner
subjects:
  - kind: ServiceAccount
    name: owner
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: cluster-owner
  apiGroup: rbac.authorization.k8s.io
