apiVersion: v1
kind: Secret
metadata:
  name: user1-sa-token
  namespace: user1
  annotations:
    kubernetes.io/service-account.name: user1-sa
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: user2-sa-token
  namespace: user2
  annotations:
    kubernetes.io/service-account.name: user2-sa
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: user3-sa-token
  namespace: user3
  annotations:
    kubernetes.io/service-account.name: user3-sa
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: user4-sa-token
  namespace: user4
  annotations:
    kubernetes.io/service-account.name: user4-sa
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: Secret
metadata:
  name: user5-sa-token
  namespace: user5
  annotations:
    kubernetes.io/service-account.name: user5-sa
type: kubernetes.io/service-account-token
